# Generated by Django 2.2 on 2020-04-30 13:58

import classes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('instructor', models.CharField(max_length=50)),
                ('toDo', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(upload_to=classes.models.image_folder)),
            ],
        ),
    ]
