# Generated by Django 2.2 on 2020-04-30 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmodel',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='classmodel',
            name='toDo',
        ),
    ]
