# Generated by Django 2.2 on 2020-06-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classmodel_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='classmodel',
            name='toDo',
        ),
        migrations.AddField(
            model_name='classmodel',
            name='homework',
            field=models.ManyToManyField(to='classes.HomeworkModel'),
        ),
    ]
