# Generated by Django 2.2 on 2020-04-30 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20200430_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmodel',
            name='image',
        ),
    ]
