# Generated by Django 2.2 on 2020-05-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_remove_classmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='toDo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
