# Generated by Django 2.2 on 2020-06-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20200629_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmodel',
            name='homework',
        ),
        migrations.AddField(
            model_name='classmodel',
            name='homework',
            field=models.ManyToManyField(to='classes.HomeworkModel'),
        ),
    ]
