# Generated by Django 2.2 on 2020-06-29 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20200629_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmodel',
            name='homework',
        ),
        migrations.AddField(
            model_name='classmodel',
            name='homework',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.HomeworkModel'),
        ),
    ]
