# Generated by Django 2.2 on 2020-06-29 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_auto_20200629_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkmodel',
            name='Class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework', to='classes.ClassModel'),
        ),
    ]
