# Generated by Django 2.2 on 2020-06-29 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_auto_20200629_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkmodel',
            name='title',
        ),
    ]
