# Generated by Django 2.2 on 2020-07-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_remove_homeworkmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='deadline',
            field=models.DateTimeField(auto_now=True, verbose_name=False),
        ),
    ]
