# Generated by Django 2.2 on 2020-07-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_classmodel_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmodel',
            name='deadline',
        ),
        migrations.AddField(
            model_name='homeworkmodel',
            name='deadline',
            field=models.DateTimeField(auto_now=True, verbose_name=False),
        ),
    ]
