# Generated by Django 2.2 on 2020-07-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_auto_20200715_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkmodel',
            name='deadline',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
