# Generated by Django 2.2 on 2020-07-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_auto_20200715_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkmodel',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
