# Generated by Django 2.2 on 2020-05-10 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20200510_0807'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userProfile',
        ),
    ]
